import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEmail, IsOptional, IsString, MaxLength } from 'class-validator';

import { CONVERSATION_SUBJECT_MAX, MESSAGE_CONTENT_MAX } from '../chat.constants';

export class StartPublicChatDto {
  @ApiProperty({ description: 'Tenant slug hosting the public website' })
  @IsString()
  @MaxLength(120)
  tenant!: string;

  @ApiProperty({ description: 'Opaque browser/session identifier generated by the widget' })
  @IsString()
  @MaxLength(120)
  client_identifier!: string;

  @ApiPropertyOptional({ description: 'Visitor name' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  client_name?: string;

  @ApiPropertyOptional({ description: 'Visitor email' })
  @IsOptional()
  @IsEmail()
  client_email?: string;

  @ApiPropertyOptional({ description: 'Visitor phone' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  client_phone?: string;

  @ApiPropertyOptional({ description: 'Current property slug, when chat is started from a listing page' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  property_slug?: string;

  @ApiPropertyOptional({ description: 'Conversation subject/topic' })
  @IsOptional()
  @IsString()
  @MaxLength(CONVERSATION_SUBJECT_MAX)
  subject?: string;

  @ApiProperty({ description: 'Initial message body' })
  @IsString()
  @MaxLength(MESSAGE_CONTENT_MAX)
  message!: string;

  @ApiPropertyOptional({ description: 'Google reCAPTCHA v3 token (required when RECAPTCHA_SECRET_KEY is set)' })
  @IsOptional()
  @IsString()
  @MaxLength(4096)
  recaptcha_token?: string;
}

export class SendPublicChatMessageDto {
  @ApiProperty({ description: 'Message body' })
  @IsString()
  @MaxLength(MESSAGE_CONTENT_MAX)
  content!: string;
}
